### ISSUE TITLE
about the mesh normalization

### ISSUE THREAD

**Issue by s1752729916** [Luo-Yihao/DOPH#1]
hi,
thanks for your great work!
do we need to normalize the mesh when calculating SDF and occupancy? If so, is it normalized to the [-1,1] cube?

**Comment by Luo-Yihao** [comment]
Hi, thanks for your question! Normalization is not necessary for the original algorithm. But we suggest normalizing the mesh into [-1,1] (we do so in our tutorials), conforming to Torch's convention when you try to incorporate it into other deep learning frameworks.
